### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by FiscalCoder** [hta218/leohuynh.dev#43] opened 2023-09-18 08:43 UTC
using the build command always results in error

```
 !  ~/p/t/leohuynh.dev   *  bunx tsc --noEmit --incremental
libs/remark-code-block-title.server.ts:6:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(tree: Node, check: "code", visitor: BuildVisitor<Node, "code">, reverse?: boolean): undefined', gave the following error.
    Argument of type 'UnistTreeType' is not assignable to parameter of type 'Node'.
      Property 'type' is missing in type 'UnistTreeType' but required in type 'Node'.
  Overload 2 of 2, '(tree: Node, visitor: BuildVisitor<Node, Test>, reverse?: boolean): undefined', gave the following error.
    Argument of type 'UnistTreeType' is not assignable to parameter of type 'Node'.

6     return visit(tree, 'code', (node: UnistNodeType, index) => {
                   ~~~~

  node_modules/@types/unist/index.d.ts:102:5
    102     type: string;
            ~~~~
    'type' is declared here.

libs/remark-img-to-jsx.server.ts:8:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(tree: Node, check: "paragraph", visitor: BuildVisitor<Node, "paragraph">, reverse?: boolean): undefined', gave the following error.
    Argument of type 'UnistTreeType' is not assignable to parameter of type 'Node'.
  Overload 2 of 2, '(tree: Node, visitor: BuildVisitor<Node, Test>, reverse?: boolean): undefined', gave the following error.
    Argument of type 'UnistTreeType' is not assignable to parameter of type 'Node'.

8     return visit(tree, 'paragraph', (node: UnistNodeType) => {
                   ~~~~


libs/remark-img-to-jsx.server.ts:19:19 - error TS2339: Property 'type' does not exist on type 'UnistImageNode'.

19         imageNode.type = 'mdxJsxFlowElement'
                     ~~~~

libs/remark-img-to-jsx.server.ts:41:14 - error TS2339: Property 'type' does not exist on type 'UnistNodeType'.

41         node.type = 'div'
                ~~~~

libs/remark-toc-heading.server.ts:16:16 - error TS2339: Property 'data' does not exist on type 'UnistNodeType'.

16     data: node.data,
                  ~~~~

libs/remark-toc-heading.server.ts:46:8 - error TS2339: Property 'data' does not exist on type 'UnistNodeType'.

46   node.data = node.data || {}
          ~~~~

libs/remark-toc-heading.server.ts:46:20 - error TS2339: Property 'data' does not exist on type 'UnistNodeType'.

46   node.data = node.data || {}
                      ~~~~

libs/remark-toc-heading.server.ts:47:8 - error TS2339: Property 'data' does not exist on type 'UnistNodeType'.

47   node.data.hProperties = node.data.hProperties || {}
          ~~~~

libs/remark-toc-heading.server.ts:47:32 - error TS2339: Property 'data' does not exist on type 'UnistNodeType'.

47   node.data.hProperties = node.data.hProperties || {}
                                  ~~~~

libs/remark-toc-heading.server.ts:62:11 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(tree: Node, check: "heading", visitor: BuildVisitor<Node, "heading">, reverse?: boolean): undefined', gave the following error.
    Argument of type 'UnistTreeType' is not assignable to parameter of type 'Node'.
  Overload 2 of 2, '(tree: Node, visitor: BuildVisitor<Node, Test>, reverse?: boolean): undefined', gave the following error.
    Argument of type 'UnistTreeType' is not assignable to parameter of type 'Node'.

62     visit(tree, 'heading', (node: UnistNodeType) => {
             ~~~~


types/server.ts:42:40 - error TS2315: Type 'Node' is not generic.

42 export interface UnistTreeType extends Node<Data> {
                                          ~~~~~~~~~~

types/server.ts:43:13 - error TS2315: Type 'Node' is not generic.

43   children: Node<Data>[]
               ~~~~~~~~~~

types/server.ts:45:40 - error TS2315: Type 'Node' is not generic.

45 export interface UnistNodeType extends Node<Data> {
                                          ~~~~~~~~~~

types/server.ts:47:13 - error TS2315: Type 'Node' is not generic.

47   children: Node<Data>[]
               ~~~~~~~~~~


Found 14 errors in 4 files.

Errors  Files
     1  libs/remark-code-block-title.server.ts:6
     3  libs/remark-img-to-jsx.server.ts:8
     6  libs/remark-toc-heading.server.ts:16
     4  types/server.ts:42
```

**Comment by hta218** [comment] 2023-09-21 01:40
Hey @FiscalCoder, I haven't tested the server build with `bun`. I'm working on a nodejs environment and things seem to work fine (`build` & `typecheck`). How did you run the `build` command?

**Comment by hta218** [comment] 2023-09-26 22:29
Since it's not reproducible and the pr no longer active, I'll close this.

**Closed by hta218** 2023-09-26 22:29 UTC
